### ISSUE TITLE
data preprocess script for training on new dataset

### ISSUE THREAD

**Issue by BinFengPKU** [sc8668/RTMScore#5]
Thank you for your nice work, I want to train the model on my own dataset, could you please provide me the script to build the graph from pdb files?

**Comment by sc8668** [comment]
you can use the script RTMScore/RTMScore/feats/mol2graph_rdmda_res.py to generate the graph from pdb files.

**Comment by pmorerio** [comment]
Hi, I have been trying to use the script as well, however it looks like data are prepared in a different way.
Below you find two examples of data extracted by the `.bin` files you provided on zenodo (https://zenodo.org/record/6859325#.Y1ayTtJBxH5) and the ones generated by the script. Looks like the graphs have different features dimensions. The first graphs (provided) works for training the model. In fact, the second example give a runtime mismatch error in cuda.

Thank you for your time an help.

```
('3d0e', Graph(num_nodes=31, num_edges=68,
      ndata_schemes={'atom': Scheme(shape=(41,), dtype=torch.float64), 'pos': Scheme(shape=(3,), dtype=torch.float64)}
      edata_schemes={'bond': Scheme(shape=(10,), dtype=torch.int64)}), Graph(num_nodes=99, num_edges=2812,
      ndata_schemes={'feats': Scheme(shape=(41,), dtype=torch.float64), 'ca_pos': Scheme(shape=(3,), dtype=torch.float32), 'center_pos': Scheme(shape=(3,), dtype=torch.float64), 'pos': Scheme(shape=(24, 3), dtype=torch.float64)}
      edata_schemes={'feats': Scheme(shape=(5,), dtype=torch.float64)}))
('03168_2FWZ', Graph(num_nodes=28, num_edges=62,
      ndata_schemes={'pos': Scheme(shape=(3,), dtype=torch.float64), 'atom': Scheme(shape=(38,), dtype=torch.int64)}
      edata_schemes={'bond': Scheme(shape=(6,), dtype=torch.int64)}), Graph(num_nodes=158, num_edges=5072,
      ndata_schemes={'pos': Scheme(shape=(24, 3), dtype=torch.float64), 'feats': Scheme(shape=(41,), dtype=torch.float64)}
      edata_schemes={'feats': Scheme(shape=(5,), dtype=torch.float64)}))
```

Error in CUDNN
```
** On entry to SGEMM  parameter number 10 had an illegal value
Traceback (most recent call last):
  File "train_model.py", line 116, in <module>
    total_loss_train, mdn_loss_train, atom_loss_train, bond_loss_train = run_a_train_epoch(epoch, model, train_loader, optimizer, aux_weight=args["aux_weight"], device=args["device"])
  File "/home/pmorerio/code/RTMScore/scripts/../RTMScore/model/utils.py", line 522, in run_a_train_epoch
    pi, sigma, mu, dist, atom_types, bond_types, batch = model(bgp, bgl)
  File "/home/pmorerio/anaconda3/envs/rtmscore/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pmorerio/code/RTMScore/scripts/../RTMScore/model/model2.py", line 499, in forward
    h_l = self.lig_model(bgl, bgl.ndata['atom'].float(), bgl.edata['bond'].float())
  File "/home/pmorerio/anaconda3/envs/rtmscore/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pmorerio/code/RTMScore/scripts/../RTMScore/model/model2.py", line 444, in forward
    node_feats = self.node_encoder(node_feats)
  File "/home/pmorerio/anaconda3/envs/rtmscore/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/pmorerio/anaconda3/envs/rtmscore/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/pmorerio/anaconda3/envs/rtmscore/lib/python3.8/site-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

**Comment by sc8668** [comment]
Are you  exactly use the script RTMScore/RTMScore/feats/mol2graph_rdmda_res.py to generate the graphs? I think the same results can be obtained if you directly use this script.  Some changes may have been made for my script.

> Hi, I have been trying to use the script as well, however it looks like data are prepared in a different way. Below you find two examples of data extracted by the `.bin` files you provided on zenodo an(https://zenodo.org/record/6859325#.Y1ayTtJBxH5) and the ones generated by the script. Looks like the graphs have different features dimensions. The first graphs (provided) works for training the model. In fact, the second example give a runtime mismatch error in cuda.
> 
> Thank you for your time an help.
> 
> ```
> ('3d0e', Graph(num_nodes=31, num_edges=68,
>       ndata_schemes={'atom': Scheme(shape=(41,), dtype=torch.float64), 'pos': Scheme(shape=(3,), dtype=torch.float64)}
>       edata_schemes={'bond': Scheme(shape=(10,), dtype=torch.int64)}), Graph(num_nodes=99, num_edges=2812,
>       ndata_schemes={'feats': Scheme(shape=(41,), dtype=torch.float64), 'ca_pos': Scheme(shape=(3,), dtype=torch.float32), 'center_pos': Scheme(shape=(3,), dtype=torch.float64), 'pos': Scheme(shape=(24, 3), dtype=torch.float64)}
>       edata_schemes={'feats': Scheme(shape=(5,), dtype=torch.float64)}))
> ('03168_2FWZ', Graph(num_nodes=28, num_edges=62,
>       ndata_schemes={'pos': Scheme(shape=(3,), dtype=torch.float64), 'atom': Scheme(shape=(38,), dtype=torch.int64)}
>       edata_schemes={'bond': Scheme(shape=(6,), dtype=torch.int64)}), Graph(num_nodes=158, num_edges=5072,
>       ndata_schemes={'pos': Scheme(shape=(24, 3), dtype=torch.float64), 'feats': Scheme(shape=(41,), dtype=torch.float64)}
>       edata_schemes={'feats': Scheme(shape=(5,), dtype=torch.float64)}))
> ```
> 
> Error in CUDNN
> 
> ```
> ** On entry to SGEMM  parameter number 10 had an illegal value
> Traceback (most recent call last):
>   File "train_model.py", line 116, in <module>
>     total_loss_train, mdn_loss_train, atom_loss_train, bond_loss_train = run_a_train_epoch(epoch, model, train_loader, optimizer, aux_weight=args["aux_weight"], device=args["device"])
>   File "/home/pmorerio/code/RTMScore/scripts/../RTMScore/model/utils.py", line 522, in run_a_train_epoch
>     pi, sigma, mu, dist, atom_types, bond_types, batch = model(bgp, bgl)
>   File "/home/pmorerio/anaconda3/envs/rtmscore/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/pmorerio/code/RTMScore/scripts/../RTMScore/model/model2.py", line 499, in forward
>     h_l = self.lig_model(bgl, bgl.ndata['atom'].float(), bgl.edata['bond'].float())
>   File "/home/pmorerio/anaconda3/envs/rtmscore/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/pmorerio/code/RTMScore/scripts/../RTMScore/model/model2.py", line 444, in forward
>     node_feats = self.node_encoder(node_feats)
>   File "/home/pmorerio/anaconda3/envs/rtmscore/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/pmorerio/anaconda3/envs/rtmscore/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 96, in forward
>     return F.linear(input, self.weight, self.bias)
>   File "/home/pmorerio/anaconda3/envs/rtmscore/lib/python3.8/site-packages/torch/nn/functional.py", line 1847, in linear
>     return torch._C._nn.linear(input, weight, bias)
> RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
> ```

**Comment by pmorerio** [comment]
Yes, I have used the script `RTMScore/RTMScore/feats/mol2graph_rdmda_res.py` to generate the second graph (`03168_2FWZ`), while the firs graph (`3d0e`) was stored inside ` v2020_train_l.bin` provided on zenodo at https://zenodo.org/record/6859325#.Y1ayTtJBxH5. With the graphs provided on zenodo I am able to retrain the model, while I get errors with the graphs generated by your script. Maybe you have used a different script to generate ` v2020_train_l.bin`?

**Comment by sc8668** [comment]
I know, you should set use_chirality=True and explicit_H=False.

**Comment by pmorerio** [comment]
Ok, thank you very much, I will try that!

**Comment by pmorerio** [comment]
Definitely works, thank you.

**Comment by kuku609** [comment]
> explicit_H=False.
Hi, I am facing the following problem while using this script to process the data, why is this problem occurring, can you give me some advice on how to solve it?
`[15:36:01] Explicit valence for atom # 264 O, 4, is greater than permitted
4bgy failed to generare the graph
[15:36:03] Explicit valence for atom # 645 C, 6, is greater than permitted
2q8i failed to generare the graph
[15:36:03] Explicit valence for atom # 36 O, 3, is greater than permitted
1ws1 failed to generare the graph
[15:36:10] Can't kekulize mol.  Unkekulized atoms: 33 34 35 37 38
[15:36:10] sanitize [15:36:10] 3v9b_ligand: 3v9b failed to generare the graph
[15:36:11] Explicit valence for atom # 490 O, 4, is greater than permitted
1cps failed to generare the graph
[15:36:12] 1w70_ligand: Warning - no explicit hydrogens in mol2 file but needed for formal charge estimation.
[15:36:24] Explicit valence for atom # 215 O, 3, is greater than permitted
4yzm failed to generare the graph
[15:36:31] Explicit valence for atom # 69 O, 3, is greater than permitted
1q4x failed to generare the graph
[15:36:31] Explicit valence for atom # 538 O, 3, is greater than permitted
1g7v failed to generare the graph
[15:36:32] Explicit valence for atom # 776 O, 3, is greater than permitted
3r2a failed to generare the graph
[15:36:32] Unusual charge on atom 25 number of radical electrons set to zero
3p3h failed to generare the graph
[15:36:45] Explicit valence for atom # 615 O, 3, is greater than permitted
6g6z failed to generare the graph
[15:36:52] 2rk7_ligand: Warning - no explicit hydrogens in mol2 file but needed for formal charge estimation.
`
